[package]
name = "nrn"
version = "0.1.0"
edition = "2024"

[features]
io = ["hdf5-metno", "serde_json", "serde", "ndarray/serde", "image", "png", "gif"]
charts = ["plotters"]

[dependencies]
ndarray = { version = "0.16.1" }
ndarray-rand = "0.15.0"
once_cell = "1.21.3"
inventory = "0.3"

hdf5-metno = { version = "0.10.1", optional = true }
serde_json = { version = "1.0.140", optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }
image = { version = "0.25.8", optional = true }
png = { version = "0.18.0", optional = true }
gif = { version = "0.13.1", optional = true }
plotters = { version = "0.3.7", optional = true }