[package]
name = "nrn"
version = "0.1.0"
edition = "2024"

[features]
synth = []
scalers = []
storage = ["hdf5-metno", "serde_json", "serde", "ndarray/serde"]

[dependencies]
ndarray = { version = "0.16.1" }
ndarray-rand = "0.15.0"
once_cell = "1.21.3"
inventory = "0.3"

hdf5-metno = { version = "0.10.1", optional = true }
serde_json = { version = "1.0.140", optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }