[package]
name = "nrn-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
nrn = { path = "../core" }
hdf5-metno = "0.10.1"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
ndarray = { version = "0.16.1", features = ["serde"] }
